const key = {
    SELECT_TYPE_IP: 'SELECT_TYPE_IP',
    OPEN_MODAL_COURSE: "OPEN_MODAL_COURSE",
    TOGGLE_MENU: "TOGGLE_MENU",
    TEXT_SEARCH: "TEXT_SEARCH",
    OPEN_MODAL_LOP: "OPEN_MODAL_LOP",
    OPEN_MODAL_DETAIL: "OPEN_MODAL_DETAIL",
    COURSE_ID:"COURSE_ID",
    TEACHER_ID:"TEACHER_ID",
    HOCKY_ID:"HOCKY_ID",
    LOAD_DATA:"LOAD_DATA",
    SELECT_HOCKY:'SELECT_HOCKY',
}
export default key;